# snakemake run example:
# snakemake -j 32 --local-cores 8 --cluster-config cluster.json --cluster "qsub -k eo -m n -l nodes=1:ppn={cluster.n} -l mem={cluster.mem}gb -l walltime={cluster.time}" --directory "$@"


import os
# import yaml
#
# with open(paths_fp, 'r') as f:
#     paths = yaml.load(f)
configfile: "../../paths.yml"

rule all:
    inputs:
        outputs

rule PDB_match:
    input:
        expand('{seq}.fasta', seq=SEQUENCES)
    output:
        'pdb_match'
    shell:
        ''

rule domain_split:
    input:
        ''
    output:
        ''
    shell:
        ''

rule generate_MSA:
    input:
        ''
    output:
        ''
    shell:
        ''
